# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dto_pb2 as dto__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dto_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MagmaServiceStub(object):
    """Exemplo de serviço gRPC que consome e retorna os seus DTOs
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessAction = channel.unary_unary(
                '/magma.MagmaService/ProcessAction',
                request_serializer=dto__pb2.RequestDTO.SerializeToString,
                response_deserializer=dto__pb2.ResponseDTO.FromString,
                _registered_method=True)


class MagmaServiceServicer(object):
    """Exemplo de serviço gRPC que consome e retorna os seus DTOs
    """

    def ProcessAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MagmaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessAction,
                    request_deserializer=dto__pb2.RequestDTO.FromString,
                    response_serializer=dto__pb2.ResponseDTO.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'magma.MagmaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('magma.MagmaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MagmaService(object):
    """Exemplo de serviço gRPC que consome e retorna os seus DTOs
    """

    @staticmethod
    def ProcessAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/magma.MagmaService/ProcessAction',
            dto__pb2.RequestDTO.SerializeToString,
            dto__pb2.ResponseDTO.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
