# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dto.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdto.proto\x12\x05magma\"S\n\nRequestDTO\x12\x0f\n\x07request\x18\x01 \x01(\t\x12\x13\n\x0btransaction\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\t\"T\n\x0bResponseDTO\x12\x0f\n\x07request\x18\x01 \x01(\t\x12\x13\n\x0btransaction\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t2F\n\x0cMagmaService\x12\x36\n\rProcessAction\x12\x11.magma.RequestDTO\x1a\x12.magma.ResponseDTOb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTDTO']._serialized_start=20
  _globals['_REQUESTDTO']._serialized_end=103
  _globals['_RESPONSEDTO']._serialized_start=105
  _globals['_RESPONSEDTO']._serialized_end=189
  _globals['_MAGMASERVICE']._serialized_start=191
  _globals['_MAGMASERVICE']._serialized_end=261
# @@protoc_insertion_point(module_scope)
